namespace UI.ShopSkins
{
    public enum CarSkins
    {
        BuggyLvl0 = 0,
        BuggyLvl1 = 1,
        BuggyLvl2 = 2,
        BuggyLvl3 = 3,
        BuggyLvl4,
        BeetleLvl0,
        BeetleLvl1,
        BeetleLvl2,
        BeetleLvl3,
        BeetleLvl4,
        ForcedLvl0,
        ForcedLvl1,
        ForcedLvl2,
        ForcedLvl3,
        ForcedLvl4,
        BeronaLvl0,
        BeronaLvl1,
        BeronaLvl2,
        BeronaLvl3,
        BeronaLvl4,
        CamaraLvl0,
        CamaraLvl1,
        CamaraLvl2,
        CamaraLvl3,
        CamaraLvl4,
        EmpuraLvl0,
        EmpuraLvl1,
        EmpuraLvl2,
        EmpuraLvl3,
        EmpuraLvl4,
        SecretLvl0,
        SecretLvl1,
        SecretLvl2,
        SecretLvl3,
        SecretLvl4,
        PudraLvl0,
        PudraLvl1,
        PudraLvl2,
        PudraLvl3,
        PudraLvl4,
        NurlatLvl0,
        NurlatLvl1,
        NurlatLvl2,
        NurlatLvl3,
        NurlatLvl4,
        CuramLvl0,
        CuramLvl1,
        CuramLvl2,
        CuramLvl3,
        CuramLvl4,
        BasDesLvl0,
        BasDesLvl1,
        BasDesLvl2,
        BasDesLvl3,
        BasDesLvl4
    }
}